### ISSUE TITLE
Add command to fix indentation

### ISSUE THREAD

**Issue by urayoru113** [yaegassy/coc-pylsp#10]
Thank for contributing this project.
Could you add a command to fix indentation like ale `ALEFix` do.

about ale: https://github.com/dense-analysis/ale

**example**

In `coc-settings.json`
```
pylsp.fixers: ['yapf', 'isort']
```

do
`:pylsy.fixing`
fix indentation in vim buffer

**Comment by yaegassy** [comment]
It may be possible to support this, but adding a command that supports execution of multiple cli commands is not easy. :(

It is not an add coc-command approach, but `coc-diagnostic` supports multiple commands, so you can try that.

- <https://github.com/iamcco/coc-diagnostic>
