### ISSUE TITLE
vim-coc does not produce any diagnostic with linters using coc-pylsp

### ISSUE THREAD

**Issue by Onturenio** [yaegassy/coc-pylsp#15]
I'm setting up vim-coc. I have installed coc-pylsp. I have been using it for a couple of days and it works OK. It YAPF didn't work, though. Trying to fix it, I have been changing some few things and suddenly now it does not work at all, and I don't know how to get back to my former setup.

I can browse the code, go to definition and all this. The LSP seems to work. But the linter part does not work. I was using flakes8 and pydocstyle, but now I get no errors at all.

My tries so far are:

The command `:CocDiagnostics` shows nothing.

`:CocList extensions` shows
```
* @yaegassy/coc-pylsp 0.9.3
```

`:CocList services` shows
```
 * pylsp [running] python  
```

And my coc-settings.json is:
```json
{
"pylsp.plugins.pycodestyle.enabled": false,
"pylsp.plugins.flake8.enabled": true,
"pylsp.plugins.flake8.ignore": ["E265", "E266"],
"pylsp.plugins.pydocstyle.enabled": true,
"pylsp.plugins.yapf.enabled": true,
"diagnostic.messageTarget": "float",
"diagnostic.checkCurrentLine": true
}
```

How can I debug this? How can I show what part is missconfigured?

**Comment by yaegassy** [comment]
How are you installing pylsp? Is it through the installer provided by coc-pylsp? In that case, please run the `:CocCommand pylsp.builtin.install` command and reinstall pylsp.

If you installed pylsp using pip install on your own, the installation method may be affecting it.

If you installed it using `pip install python-lsp-server`, `yapf` and `flake8` are not installed. You need to install them using `pip install "python-lsp-server[all]"`.

For more details, please refer to the pylsp's README.

- <https://github.com/python-lsp/python-lsp-server>

**Comment by Onturenio** [comment]
Thanks for the fast reply. I tried re-running pip install "python-lsp-server[all]" and it worked. But it is not fully clear to me why. What happens when you run `pylsp.builtin.install` and how it differs from running pip yourself? Is the server installed in a different environment? If so, how coc-pylsp knows where to find packages?

Thanks for the clarification. Perhaps you might considering expanding the explanations in the documentation. For noobs in coc.nvim like me, I find all this a bit confusing.

Thanks for the nice work in any case!

**Comment by yaegassy** [comment]
The detection order of pylsp used by coc-pylsp.

- <https://github.com/yaegassy/coc-pylsp#detect-pylsp-python-lsp-server>
