### ISSUE TITLE
I cannot run isort

### ISSUE THREAD

**Issue by Onturenio** [yaegassy/coc-pylsp#16]
I'm trying to run **isort** my my code. I have the following configuration:

```
{
"pylsp.plugins.pycodestyle.enabled": false,
"pylsp.plugins.flake8.enabled": false,
"pylsp.plugins.flake8.ignore": ["E265", "E266"],
"pylsp.plugins.pydocstyle.enabled": false,
"pylsp.plugins.mccabe.enabled": false,
"pylsp.plugins.yapf.enabled": false,
"pylsp.plugins.ruff.enabled": true,
"pylsp.plugins.ruff.extendSelect": ["D", "C90", "I"],
"pylsp.plugins.ruff.lineLength": 80,
  "pylsp.builtin.installExtrasArgs": [
    "flake8",
    "yapf",
    "mccabe",
    "pycodestyle",
    "pydocstyle",
    "pyflakes",
    "pylint",
    "rope"
  ],
"pylsp.builtin.enableInstallPythonLspRuff": true,
"pylsp.builtin.enableInstallPylsIsort": true,
"diagnostic.messageTarget": "float",
"diagnostic.checkCurrentLine": true}
```
I have installed `isort` via pip, and I think it is also in the dedicated venv? Not sure but I get this:
```

> find .config/coc/extensions/\@yaegassy/coc-pylsp-data/pylsp/ -name "*isort"
.config/coc/extensions/@yaegassy/coc-pylsp-data/pylsp/venv/bin/isort
.config/coc/extensions/@yaegassy/coc-pylsp-data/pylsp/venv/lib/python3.9/site-packages/pyls_isort
.config/coc/extensions/@yaegassy/coc-pylsp-data/pylsp/venv/lib/python3.9/site-packages/isort
```

Now, I'd like to run it. I have tried running `:CocCommand editor.action.organizeImport` but I get the error:

```
[coc.nvim] Organize import action not found 
 ```

I also tried `:call CocAction('organizeImport')` but then I get nothing, not even an error.

Thanks in advance for the help!

**Comment by yaegassy** [comment]
`pyls-isort` does not support `editor.action.organizeImport`. `pyls-isort` is executed as part of the "formatter". If you have any issues or requests regarding its behavior, it may be a good idea to make a feature request to `pylsp` or `pyls-isort` itself.

**DEMO**:

https://user-images.githubusercontent.com/188642/228412597-e1362b31-52d4-48d4-b203-7936c1c144a5.mp4
