### ISSUE TITLE
how to remove the warning: line too long

### ISSUE THREAD

**Issue by ashixu** [yaegassy/coc-pylsp#17]
Some code logic is more complicated, and newlines affect the readability of the code, so I want to cancel this restriction or increase the number of columns. How can I do that.

**Comment by yaegassy** [comment]
Which tool is reporting the warning message? Is it from `flake8` or `pycodestyle`? If it's from `flake8` or `pycodestyle`, I believe adding `# noqa` at the end of the line will suppress the warning message. https://flake8.pycqa.org/en/3.1.1/user/ignoring-errors.html

It is also possible to suppress it within configuration files like `setup.cfg`. Please consult the documentation of each tool for more information.

To suppress it using the configuration of `coc-pylsp` itself, you can utilize the `pylsp.plugins.flake8.ignore`, `pylsp.plugins.pycodestyle.ignore` and more settings.
