### ISSUE TITLE
Can I specify in the settings for coc-pylsp to use black for formatting?

### ISSUE THREAD

**Issue by xeon826** [yaegassy/coc-pylsp#19]
Looking at the trace server output, I see it's using autopep8, is there a way I can tell it to use black instead?

**Comment by yaegassy** [comment]
Check this section of the README for information on black (python-lsp-black) and give it a try. Or, you can stop autopep8 itself by setting `"pylsp.plugins.autopep8.enabled": false`

- <https://github.com/yaegassy/coc-pylsp#bult-in-install-pylsp-and-3rd-party-plugins>

**Comment by yaegassy** [comment]
The current `python-lsp-black` seems to automatically disable autopep8, etc. just by installing it. please adjust your configuration to install `python-lsp-black`.
