### ISSUE TITLE
Where are 3rd party plugins installed?

### ISSUE THREAD

**Issue by Onturenio** [yaegassy/coc-pylsp#26]
Hi, this is more a request for documentation/help than an issue. I'm using ruff via the 3rd plugin [python-lsp-ruff](https://github.com/python-lsp/python-lsp-ruff). This setup works, but I'm a bit puzzled to understand how all this works. From my user point of view, there is a relation between all the plugins like:
coc.nvim > coc-pylsp > python-lsp-ruff. Somehow I see the latter as a "subpluggin" of the former. Is this accurate? I guess no, but I'm not sure.

A very concrete problem I had for not understanding how all this is related is that recently python-lsp-ruff got updated to support `ruff format`. But as I had installed the latter via the built in installation of coc-pylsp, I could not use the latest capabilities, neither I knew how to update. More generally, I realised that I have no idea what happens when you install with the builtin installation of coc-pylsp. I cannot list python-lsp-ruff as a valid plugins, therefore I cannot update. Actually I don't even know where all this is installed at all! My solution to this was therefore to uninstall everything related to coc.nvim, delete the folders manually, and start over. Totally noob, I know.

Could you briefly explain (maybe you want to include few notes in the main README for noobs like me) the relationship between this and the 3rd party plugins? And the difference, if any, between using the builtin installation and just installing it separately? Actually, now I realise that I'm not sure if I could just install python-lsp-ruff directly without using coc-pylsp... is this possible?

Sorry if I'm making many very stupid questions. Thank you very much for the help and your great plugin!

**Comment by yaegassy** [comment]
coc-pylsp uses a language server called python-lsp-server. python-lsp-ruff is a plugin for the python-lsp-server language server.

- <https://github.com/python-lsp/python-lsp-server?tab=readme-ov-file#3rd-party-plugins>

To update python-lsp-server and python-lsp-ruff installed by coc-pylsp, run `:CocCommand pylsp.builtin.install`. This command will remove the existing ones and install the latest version.

Check below for the location where it will be installed. It will be installed in this venv environment.

- <https://github.com/yaegassy/coc-pylsp?tab=readme-ov-file#commands>

Regarding the built-in installation, there are multiple ways to install and use various packages in Python.

1. install in the system global python environment
2. create a virtual python environment for each project using venv, etc. and install there

Installing packages in system-global python may cause unexpected problems, such as conflicts with other packages. In the case of creating a venv for each project, it is necessary to install a package for each project each time. This may cause conflicts with other packages in the project, which may lead to unexpected problems.

The built-in installation of coc-pylsp creates a python virtual environment dedicated to coc-pylsp and installs the language server and other packages there to avoid these problems.

You can of course install python-lsp-server any way you like. In that case, you can use the pylsp command created after installation by adding it to coc-pylsp's `pylsp.commandPath` setting.

**Comment by yaegassy** [comment]
If you find the python-lsp-server plugin mechanism complicated, there is another approach. You want to use ruff, and there is an official language server for ruff.

The official language server is called `ruff-lsp`.

- <https://github.com/astral-sh/ruff-lsp>

I also maintain a coc-extension called coc-ruff that uses ruff-lsp, so please use that.

- <https://github.com/yaegassy/coc-ruff>
